app_affiliate:
    resource: "@AppBundle/Controller/AffiliateController.php"
    type:     annotation

api:
    resource: "@ApiBundle/Controller/"
    type:     rest
    prefix:   /api

login:
    pattern:   /login
    defaults:  { _controller: AppBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    path: /logout
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
app:
    resource: '@AppBundle/Controller/'
    type: annotation
