# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.job_uploader:
        class: AppBundle\Utils\FileUploader
        arguments: ['%jobs_directory%']
    app.doctrine_job_listener:
        class: AppBundle\EventListener\JobUploadListener
        arguments: ['@app.job_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
    app.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Jobeet, label: Categories }
 
    app.admin.job:
        class: AppBundle\Admin\JobAdmin
        arguments: [~, AppBundle\Entity\Job, AppBundle:JobAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Jobeet, label: Jobs }

    app.admin.affiliate:
        class: AppBundle\Admin\AffiliateAdmin
        arguments: [~, AppBundle\Entity\Affiliate, AppBundle:AffiliateAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Jobeet, label: Affiliates }
        